name          'doismellburning-drone'
version       '0.0.1'
source        'https://github.com/doismellburning/puppet-drone'
author        'doismellburning'
license       'MIT'
summary       'Manages a drone.io instance'
description   'Manages a drone.io instance'
project_page  'https://github.com/doismellburning/puppet-drone'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
